"""initial

Revision ID: ac0ff547c312
Revises: 
Create Date: 2024-04-27 10:43:51.105950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac0ff547c312'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_end_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oper_code', sa.Integer(), nullable=True),
    sa.Column('oper_div', sa.Integer(), nullable=True),
    sa.Column('route_code', sa.String(), nullable=True),
    sa.Column('tape_rn', sa.String(), nullable=True),
    sa.Column('term', sa.String(), nullable=True),
    sa.Column('ekl', sa.String(), nullable=True),
    sa.Column('bkl', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('date_of', sa.DateTime(), nullable=True),
    sa.Column('ins_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shift_end_info')
    # ### end Alembic commands ###
